branches:
  only: 
    - master

os:
  - osx

language: go

before_install:
  - go get github.com/mattn/goveralls
  - go get -u github.com/golang/lint/golint
  - rvm install 2.0.0
  - gem install danger
  - gem uninstall bundler -v '>1.12.5' --force || echo "bundler >1.12.5 is not installed"
  - gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet
  - danger --verbose

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

go:
  - tip
